---
title: STAT 455 Homework 05
subtitle: R-Code
author: Martha Eichlersmith
date: 2019-11-21
output:
  pdf_document:
    fig_caption: yes
    number_sections: true #give section automic numbers 
header-includes:
  - \usepackage{color}
  - \usepackage{mathtools}
  - \usepackage{amsbsy} #bold in mathmode
  - \usepackage{nicefrac} # for nice fracs 
  - \usepackage{booktabs}
  - \usepackage{geometry}
  - \usepackage{caption} #to remove automatic table name and number - \captionsetup[table]{labelformat=empty}, put code under ---
geometry: "left=1.75cm,right=1.75cm,top=1.5cm,bottom=2cm" 

---
```{r setup, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
library(ggplot2) #ggplot
library(readr) #import CSV
library(gridExtra) #organize plots
library(grid) #organize plots
library(latex2exp) #latex in ggplot titles 
library(gtable) #for tablegrob functions 
library(dplyr) #for piping 
library(xtable) #for latex table output 
knitr::opts_chunk$set(fig.width = 10, fig.height = 4)
#knitr::opts_chunk$set(echo=FALSE)
decimal <- function(x, k) trimws(format(round(x, k), nsmall=k))
  #function to round/display specific decimals
dec <- 3
```

## Put in Raw Data  
```{r rawdata}
Game <- c(1:23) #game number 
Made <- c(4, 5, 5, 5, 2, 7, 6, 9, 
          4, 1, 13, 5, 6, 9, 7, 3,
          8, 1, 18, 3, 10, 1, 3) #number of free throws made 
Attempt <- c(5, 11, 14, 12, 7, 10, 14, 15, 
             12, 4, 27, 17, 12, 9, 12, 10, 
             12, 6, 39, 13, 17, 6 ,12) #number of free throw attempt
Miss <- Attempt - Made #number of free throws missed 
Prop <- Made/Attempt #proportion made
```
  
## Convert Data to Binary Data
```{r binarydata} 
l <- length(Game) #23
FT <- c() #free throws vector (binary: 0 or 1)
G <- c() #game vector 
for (i in 1:l){
    made.i <- c(rep(1, Made[i]))
    miss.i <- c(rep(0, Miss[i]))
    new.game <- c(rep(Game[i], length(made.i)+length(miss.i)))
    FT <- c(FT, made.i, miss.i)
    G <- c(G, new.game)}
df.data <- data.frame("FT"=FT, "G"=G)
```

# Common Probability  

## Estimate $\alpha$ 
```{r reg, warning=FALSE, message=FALSE}
reg <- glm(FT~1, family=binomial(link="identity"))
alpha <- summary(reg)$coef[1,1] #pull out interecept estimation 
se.alpha <- summary(reg)$coef[1,2]#pull out standard error of incetercept estimate 
CI.alpha <- confint(reg)
print.CI.alpha <- paste(decimal(CI.alpha, dec), collapse=",")
```

```{r alpha.table}
name <- c("$\\hat{\\alpha}$"
          , "Standard Error"
          , "Confidence Interval")
value <- c(decimal(alpha, dec), 
           decimal(se.alpha, dec),
           paste("(", print.CI.alpha, ")"))
alpha.table <- data.frame("Statistic" = name, "Values" = value)
caption.alpha.table <- c("Common Probability Model -  $\\alpha$")
knitr::kable(alpha.table, align='lr',caption=paste(caption.alpha.table))
```
  
```{r alpha.tableLatex, echo=FALSE, eval=FALSE}
xtable.alpha.table <- xtable(phi.table, align="clr", caption=paste(caption.alpha.table))
print(xtable.alpha.table
      ,caption.placement="top"
      ,sanitize.text.function = function(x){x}
      )
```

## Global Lack of Fit - Chi-Squared Approximation 

```{r chiassumptions}
n.star <- sum(Attempt)
dim.H0H1 <- length(Game)
paste("Check:", n.star, "=n.star >> dim(H0 U H1)=", dim.H0H1)
```
  
```{r chisq, warning=FALSE }
table <- cbind(Made, Miss)
chi.test <- chisq.test(table)
X2 <- chi.test$statistic
pval <- chi.test$p.value
df <- chi.test$parameter 
paste("Pearson X-sq Statistic="
      , decimal(X2, dec)
      , "on"
      , df
      , "degrees of freedom, with p-value of"
      , decimal(pval, dec)
      )

```

## Local Lack of Fit - Standardized Residuals  

```{r res}
stdreschi <- chi.test$stdres[,1]#standardize residual 
big.res <- length(stdreschi[abs(stdreschi)> 2])
res.table <- cbind(Game, stdreschi)
res.table <- res.table[order(-abs(stdreschi)),]
  #put residuals in order from larges abs value to smallest abs value 
colnames(res.table) <- c("Game", "Standardized Residuals")
caption.res <- c("Common Probability Model: Standardized Residuals")
res.table
```

```{r resLatex, echo=FALSE, eval=FALSE}
xtable.res <- xtable(res.table, align="lrr", digits=c(0, 0, dec), caption=paste(caption.res))
print(xtable.res
      ,caption.placement="top"
      ,sanitize.text.function = function(x){x}
      )
```

## Game 14 - Outlier causing lack of fit? 
```{r chisq.no14, warning=FALSE }
table <- cbind(Made, Miss)
table.no14 <- table[-14,]
chi.test.no14 <- chisq.test(table.no14)
X2.no14 <- chi.test.no14$statistic
pval.no14 <- chi.test.no14$p.value
df.no14 <- chi.test.no14$parameter 
paste("Pearson X-sq Statistic="
      , decimal(X2.no14, dec)
      , "on"
      , df.no14
      , "degrees of freedom, with p-value of"
      , decimal(pval.no14, dec)
      )
```

```{r res.no14}
stdreschi <- chi.test$stdres[,1]#standardize residual 
decimal(max(abs(stdreschi)), dec) #make standardize residual in absolute vaule
```


# Common Probability Model with Over-disperion   

## Estimate Dispersion and Scale 
```{r phi}
phi <- X2/ df
paste("X2 is", decimal(X2, dec), "on", df, "df --and so phi="
      , decimal(phi, dec), "and so sqrt(phi)=", decimal(sqrt(phi), dec))
```

## Estimate $\alpha$, assuming $\phi \neq 1$ 
```{r reg.phi, warning=FALSE, message=FALSE}
reg <- glm(FT~1, family=binomial(link="identity"))
reg.phi<-  summary(reg, dispersion=phi)
alpha.phi <- reg.phi$coef[1,1]
alpha.se.phi <- reg.phi$coef[1,2]

z.star <- qnorm(0.975)
CI.phi <- cbind(alpha.phi - z.star*alpha.se.phi, alpha + z.star*alpha.se.phi)
print.CI.phi <- paste(decimal(CI.phi, dec), collapse=",")
```

```{r phi.table}
name <- c("$\\hat{\\alpha}$"
          , "Standard Error of $\\alpha$"
          , "Confidence Interval for $\\alpha$")
value <- c(decimal(alpha.phi, dec),  decimal(alpha.se.phi, dec),
           paste("(", print.CI.phi, ")"))
phi.table <- data.frame("Statistic" = name, "Values" = value)
caption.phi.table <- c("Common Probability Model assuming $\\phi \\neq 1$ - $\\alpha$")
knitr::kable(phi.table, align="lr", caption=paste(caption.phi.table))
```
```{r phi.tableLaTex, echo=FALSE, eval=FALSE}
xtable.phi.table <- xtable(phi.table, align="llr", caption=paste(caption.phi.table))
print(xtable.phi.table
      ,caption.placement="top"
      ,sanitize.text.function = function(x){x}
      )
```
  
 



