---
header-includes:
- \usepackage{color}
- \usepackage{mathtools}
- \usepackage[labelformat=empty]{caption}
- \usepackage{booktabs}
- \usepackage{geometry}
geometry: "left=1.75cm,right=1.75cm,top=1.5cm,bottom=2cm" 
output:
  pdf_document:
    fig_caption: yes
---
```{r, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
library(knitr)
library(xtable)
library(vcdExtra) #calculate Goodman_kruskal Gamma 
library(ORCI) #cornfield exact CI for odds ratio
library(DescTools) #OddsRatio()
library(epitools) #oddsratio 
decimal <- function(x, k) trimws(format(round(x, k), nsmall=k))
dec <- 4
```



# STAT 455 Homework 04 - R Code  
*Martha Eichlersmith*  
2019-11-07

## Problem 3.3
```{r}
func_Xsqcells <- function(matrix, i, j){
Y.ij <- matrix[i, j]
Y.iplus <- sum(matrix[i,])
Y.plusj <- sum(matrix[,j])
n <- sum(matrix)
m.ij <- (Y.iplus*Y.plusj)/n
(Y.ij - m.ij)^2 / m.ij}

func_chisqtest <- function(matrix){
I <- dim(matrix)[1]
J <- dim(matrix)[2]
row <- c()
for (i in 1:I){
  vec <- rep(i, J)
  row <- c(row, vec)}
col <- c(rep(c(1:J), I))
Xsq <- sum(mapply(func_Xsqcells, matrix=rep(list(matrix), length(row)), i=row, j=col))
df <- (I - 1)*(J-1)
pval <- 1- pchisq(Xsq, df)
paste("X-squared=", round(Xsq, 5), ", df=", df, ", p-value=", decimal(pval, 4))}

func_Lsqcells <- function(matrix, i, j){
Y.ij <- matrix[i, j]
Y.iplus <- sum(matrix[i,])
Y.plusj <- sum(matrix[,j])
n <- sum(matrix)
m.ij <- (Y.iplus*Y.plusj)/n
2*Y.ij*log(Y.ij/m.ij)}

func_liketest <- function(matrix){
I <- dim(matrix)[1]
J <- dim(matrix)[2]
row <- c()
for (i in 1:I){
  vec <- rep(i, J)
  row <- c(row, vec)}
col <- c(rep(c(1:J), I))
Lsq <- sum(mapply(func_Lsqcells, matrix=rep(list(matrix), length(row)), i=row, j=col))
df <- (I - 1)*(J-1)
pval <- 1- pchisq(Lsq, df)
paste("L-squared=", round(Lsq, 5), ", df=", df, ", p-value=", decimal(pval, 4))}
```
```{r}
shots <- matrix(c(251, 48, 34, 5), nrow=2, ncol=2)
func_chisqtest(shots)
func_liketest(shots)
```


## Problem 3.9a
```{r, message=FALSE, warning=FALSE}
names.r <- c("Schizophrenia", "Affective disorder", "Neurosis",
             "Personality disorder", "Special systems")
names.c <- c("Drugs", "No Drugs")
count.vec <- c(105, 12, 18, 47,  0, 8,  2, 19, 52, 13)

r <-length(names.r)
c <- length(names.c)
row <- c()
for (i in 1:r){
  vec <- rep(i, c)
  row <- c(row, vec)}

column <- c(rep(c(1:c), r))

Count<- matrix(count.vec, nrow=r, ncol=c)
rownames(Count) <- names.r 
colnames(Count) <- names.c
stdreschi <- chisq.test(Count)$stdres
t1 <- kable(Count,    format="latex", booktabs=TRUE)
t2 <- kable(stdreschi, format="latex" , booktabs=TRUE)

```

```{r, echo=FALSE, results='asis'}
cat(c("\\begin{table}[!htb]
    \\begin{minipage}{.5\\linewidth}
      \\caption{Counts}
      \\centering",
        t1,
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}
      \\centering
        \\caption{Perason Standard Residuals}",
        t2,
    "\\end{minipage} 
\\end{table}"
))  
```

```{r, eval=FALSE, echo=FALSE}
xtable(stdreschi, align='lrr')
```


## Problem 3.12
```{r}
names.r <- c("Less than highschool", "Highschool", "More than highschool")
names.c <- c("Disapprove", "Middle", "Approve")
count.vec <- c(209, 151, 16,101, 126, 21,237, 426, 138)

r <-length(names.r)
c <- length(names.c)
row <- c()
for (i in 1:r){
  vec <- rep(i, c)
  row <- c(row, vec)}
column <- c(rep(c(1:c), r))

Count<- matrix(count.vec, nrow=r, ncol=c)
gamma <- GKgamma(Count)$gamma
gammaCI <- GKgamma(Count)$CI
```
```{r, echo=FALSE}
paste("Gamma:", decimal(gamma, dec))
paste("CI: (", decimal(gammaCI[1], dec), ",", decimal(gammaCI[2], dec), ")")
```

\newpage 
## Problem 3.15  
```{r, warning=FALSE, message=FALSE}
names.r <- c("Treatment", "Control")
names.c <- c("Normal.Yes", "Normal.No")
r <-length(names.r)
c <- length(names.c)
count.vec <- count <- c(7, 8, 0, 15)
Count<- matrix(count.vec, nrow=r, ncol=c, byrow=TRUE)
rownames(Count) <- names.r 
colnames(Count) <- names.c
kable(Count, booktabs=TRUE)

n <- sum(count)
OR <- (Count[1,1]*Count[2,2]) / (Count[1,2]*Count[2,1])

#WOOLF (WALD)
A <- oddsratio(Count, conf.level=0.95, method="wald")$measure[2,2:3]

#CORNFIELD EXACT
B <- Cornfieldexact.CI(Count[1,1], sum(Count[1,]), Count[2,1], sum(Count[2,])) 

#PROFILE LIKELIHOOD
y.data <- c(rep(1, Count[1,1]), rep(0, Count[1,2]), rep(1, Count[2,1]), rep(0, Count[2,2]))
x.data <- c(rep(1, Count[1,1]), rep(1, Count[1,2]), rep(0, Count[2,1]), rep(0, Count[2,2]))
df.data <- data.frame("Y"=y.data, "X"=x.data)
logit <- glm(Y ~ X, data=df.data, family=binomial)
C <- exp(confint(logit)[2,])

D <- c(5.117, Inf)

names <- c("Woolf (Wald)", "Cornfield Exact", "Profile Likelihood", "Profile Likelihood, SAS")
results<- cbind( names, decimal(rbind(A, B, C, D), dec))
rownames(results) <- c("A", "B", "C", "D")
colnames(results) <- c("Name", "CI Lower", "CI Uppder")

kable(results, align='lrrr', booktabs=TRUE)
```


```{r, echo=FALSE, eval=FALSE}
xtable(results)
```


```{r, message=FALSE, eval=FALSE, echo=FALSE }
#In class example to check to see if getting correct values 
names.r <- c("Risk=Y", "Risk=N")
names.c <- c("Disease=Y", "Disease=N")
r <-length(names.r)
c <- length(names.c)
count.vec <- count <- c(18, 193, 8, 281)
Count<- matrix(count.vec, nrow=r, ncol=c, byrow=TRUE)
rownames(Count) <- names.r 
colnames(Count) <- names.c
kable(Count, booktabs=TRUE)

n <- sum(count)
OR <- (Count[1,1]*Count[2,2]) / (Count[1,2]*Count[2,1])

#WOOLF (WALD)
A <- oddsratio(Count, conf.level=0.95, method="wald")$measure[2,2:3]

#CORNFIELD EXACT
B <- Cornfieldexact.CI(Count[1,1], sum(Count[1,]), Count[2,1], sum(Count[2,])) 

#PROFILE LIKELIHOOD
y.data <- c(rep(1, Count[1,1]), rep(0, Count[1,2]), rep(1, Count[2,1]), rep(0, Count[2,2]))
x.data <- c(rep(1, Count[1,1]), rep(1, Count[1,2]), rep(0, Count[2,1]), rep(0, Count[2,2]))
df.data <- data.frame("Y"=y.data, "X"=x.data)
logit <- glm(Y ~ X, data=df.data, family=binomial)
C <- exp(confint(logit)[2,])

#put it alll in a tabbble
names <- c("Woolf (Wald)", "Cornfield Exact", "Profile Likelihood")
results<- cbind(names, rbind(decimal(A, dec), decimal(B, dec), decimal(C, dec)))
rownames(results) <- c("A", "B", "C")
colnames(results) <- c("", "CI Lower", "CI Uppder")

kable(results, align='lrrr', booktabs=TRUE)
```

\newpage 
## Problem 3.31
```{r}
func_Xsqcells.iid <- function(matrix, i, j){
n.ij <- matrix[i, j]
n <- sum(matrix)
p.1plus <- sum(matrix[1,])/n
p.plus1 <- sum(matrix[,1])/n
theta <- (p.1plus + p.plus1) / 2
if (i==1 & j==1) {mu.hat <- n * theta^2}
if (i==1 & j==2) {mu.hat <- n * theta * (1 - theta)}
if (i==2 & j==1) {mu.hat <- n * theta * (1 - theta)}
if (i==2 & j==2) {mu.hat <- n * (1 - theta)^2 }
(n.ij - mu.hat)^2 / mu.hat }

func_chisqtest.iid <- function(matrix){
I <- dim(matrix)[1]
J <- dim(matrix)[2]
row <- c()
for (i in 1:I){
  vec <- rep(i, J)
  row <- c(row, vec)}
col <- c(rep(c(1:J), I))
Xsq <- sum(mapply(func_Xsqcells.iid, matrix=rep(list(matrix), length(row)), i=row, j=col))
df <- sum(dim(matrix)) - 2
pval <- 1- pchisq(Xsq, df)
paste("X-squared=", round(Xsq, 5), ", df=", df, ", p-value=", decimal(pval, 4))}
```

```{r}
shots <- matrix(c(251, 48, 34, 5), nrow=2, ncol=2)
func_chisqtest(shots)
func_chisqtest.iid(shots)
```











```{r, echo=FALSE, eval=FALSE}
#EXTRA WORK FOR 3.15, DIFFERENT WAYS OF CALCULATING CONFIDENCE INTERVAL 
#WOOLF'S CI
se_log <- sqrt(  sum(1/count))
z.star <- qnorm(0.975, 0, 1)
CI.up_log <- log(OR) + z.star*se_log
CI.low_log <- log(OR) - z.star*se_log
CI.up <- exp(CI.up_log)
CI.low <- exp(CI.low_log)
Woolf_CI <- c(CI.low, CI.up)
paste("OR:", decimal(OR, dec))
paste("Woolf CI Interval: (", decimal(Woolf_CI[1], dec), ",", decimal(Woolf_CI[2], dec), ")")

#CORNFIELD EXACT 
x1 <- Count[1, 1]    # 7
n1 <- sum(Count[1,]) #15
x2 <- Count[2, 1]    # 0
n2 <- sum(Count[2,]) #15
round(Cornfieldexact.CI(x1, n1, x2, n2, conf=0.95), 4)
round(OddsRatio(Count, conf.level=0.95, method="mle"), 4) #get exact conf-interval (cornfield)
round(OddsRatio((Count+0.5), conf.level=0.95, method="mle"), 4) #close to the value when you do it in SAS (2.6460, infty)


#Profile Likelihood
Count <- matrix(c(18, 8, 193, 281), nrow=2, ncol=2)
#count.vec <- c(7, 8, 0, 15)
#count.vec <- count.vec + 1
#Count <- matrix(count.vec, nrow=2, ncol=2)
oddsratio(Count, conf.level=0.95, method="fisher")$measure[2,]
#OddsRatio(Count, conf.level=0.95, method="midp", correction=TRUE)
```




